DROP TABLE IF EXISTS DEPENDENT;
DROP TABLE IF EXISTS WORKS_ON;
DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS DEPT_LOCATIONS;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
	Fname VARCHAR(15) NOT NULL,
    Minit CHAR(1) NULL,
    Lname VARCHAR(15) NOT NULL,
    Ssn CHAR(9) NOT NULL,
    Bdate VARCHAR(15) NULL,
    Address VARCHAR(30) NULL,
    Sex CHAR(1) NULL,
    Salary DECIMAL(10, 2) NULL,
    Super_ssn CHAR(9) NULL,
    Dno INT NOT NULL,
    CONSTRAINT EMPPK PRIMARY KEY (Ssn),
    CONSTRAINT EMPSUPERFK FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE (Ssn) 
);


CREATE TABLE DEPARTMENT (
	Dname VARCHAR(15) NOT NULL,
    Dnumber INT NOT NULL,
    Mgr_ssn CHAR(9) NOT NULL,
    Mgr_start_date VARCHAR(15) NOT NULL,
    CONSTRAINT DEPTPK PRIMARY KEY (Dnumber),
    CONSTRAINT DEPTUK UNIQUE (Dname),
    CONSTRAINT DEPTMGRFK FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE (Ssn) 
);

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT EMPDEPTFK FOREIGN KEY (Dno)
REFERENCES DEPARTMENT (Dnumber);


CREATE TABLE DEPT_LOCATIONS (
	Dnumber INT NOT NULL,
    Dlocation VARCHAR(15) NOT NULL,
    CONSTRAINT DEPTLOCPK PRIMARY KEY (Dnumber, Dlocation),
    CONSTRAINT DEPTLOCNUMFK FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT (Dnumber) 
);


CREATE TABLE PROJECT (
	Pname VARCHAR(25) NOT NULL,
    Pnumber INT NOT NULL,
    Plocation VARCHAR(25) NULL,
    Dnum INT NOT NULL,
    CONSTRAINT PROJPK PRIMARY KEY (Pnumber),
    CONSTRAINT PROJUK UNIQUE (Pname),
    CONSTRAINT PROJNUMFK FOREIGN KEY (Dnum) REFERENCES DEPARTMENT (Dnumber) 
);


CREATE TABLE WORKS_ON (
	Essn CHAR(9) NOT NULL,
    Pno INT NOT NULL,
    Hours DECIMAL(3,1) NULL,
    CONSTRAINT WORKPK PRIMARY KEY (Essn, Pno),
    CONSTRAINT WORKESSNFK FOREIGN KEY (Essn) REFERENCES EMPLOYEE (Ssn),
    CONSTRAINT WORKPNOFK FOREIGN KEY (Pno) REFERENCES PROJECT (Pnumber)
);


CREATE TABLE DEPENDENT (
	Essn CHAR(9) NOT NULL,
    Dependent_name VARCHAR(15) NOT NULL,
    Sex CHAR(1) NULL,
    Bdate VARCHAR(15) NULL,
    Relationship VARCHAR(8) NULL,
    CONSTRAINT DEPNTPK PRIMARY KEY (Essn, Dependent_name),
    CONSTRAINT DEPNTFK FOREIGN KEY (Essn) REFERENCES EMPLOYEE (Ssn)
);
