DROP DATABASE IF EXISTS COMPANY;
CREATE DATABASE COMPANY;
USE COMPANY;

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
	Fname VARCHAR(20) NOT NULL,
    Minit CHAR(1) NULL,
    Lname VARCHAR(20) NOT NULL,
    Ssn CHAR(9) NOT NULL,
    Bdate VARCHAR(11) NULL,
    Address VARCHAR(50) NULL,
    Sex CHAR(1) NULL,
    Salary DECIMAL(10, 2) NULL,
    Super_ssn CHAR(9) NULL,
    Dno INT NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (Ssn),
    CONSTRAINT FK_EMPLOYEE_EMPLOYEE FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE (Ssn)
);

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT (
	Dname VARCHAR(50) NOT NULL,
    Dnumber INT NOT NULL,
    Mgr_ssn CHAR(9) NOT NULL,
    Mgr_start_date VARCHAR(11) NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (Dnumber),
    CONSTRAINT FK_DEPARTMENT_EMPLOYEE FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE (Ssn)
);

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_DEPARTMENT FOREIGN KEY (Dno)
REFERENCES DEPARTMENT (Dnumber);

DROP TABLE IF EXISTS DEPT_LOCATIONS;
CREATE TABLE DEPT_LOCATIONS (
	Dnumber INT NOT NULL,
    Dlocation VARCHAR(50) NOT NULL,
    CONSTRAINT PK_DEPT_LOCATIONS PRIMARY KEY (Dnumber, Dlocation),
    CONSTRAINT FK_DEPT_LOCATIONS_DEPARTMENT FOREIGN KEY (Dnumber)
    REFERENCES DEPARTMENT (Dnumber)
);

DROP TABLE IF EXISTS PROJECT;
CREATE TABLE PROJECT (
	Pname VARCHAR(30) NOT NULL,
    Pnumber INT NOT NULL,
    Plocation VARCHAR(50) NULL,
    Dnum INT NOT NULL,
    CONSTRAINT PK_PROJECT PRIMARY KEY (Pnumber),
    CONSTRAINT UK_PROJECT UNIQUE (Pname),
    CONSTRAINT FK_PROJECT_DEPARTMENT FOREIGN KEY (Dnum) REFERENCES DEPARTMENT (Dnumber)
);

DROP TABLE IF EXISTS WORKS_ON;
CREATE TABLE WORKS_ON (
	Essn CHAR(9) NOT NULL,
    Pno INT NOT NULL,
    Hours DECIMAL(3,1) NULL,
    CONSTRAINT PK_WORKS_ON PRIMARY KEY (Essn, Pno),
    CONSTRAINT FK_WORKS_ON_EMPLOYEE FOREIGN KEY (Essn)
    REFERENCES EMPLOYEE (Ssn),
    CONSTRAINT FK_WORKS_ON_PROJECT FOREIGN KEY (Pno)
    REFERENCES PROJECT (Pnumber)
);

DROP TABLE IF EXISTS DEPENDENT;
CREATE TABLE DEPENDENT (
	Essn CHAR(9) NOT NULL,
    Dependent_name VARCHAR(30) NOT NULL,
    Sex CHAR(1) NULL,
    Bdate VARCHAR(11) NULL,
    Relationship VARCHAR(10) NULL,
    CONSTRAINT PK_DEPENDENT PRIMARY KEY (Essn, Dependent_name),
    CONSTRAINT FK_DEPENDENT_EMPLOYEE FOREIGN KEY (Essn)
    REFERENCES EMPLOYEE (Ssn)
);
